version: "3.9"
   
services:
  web:
    build:
      context: .
      dockerfile: docker-build/Dockerfile
    command: /bin/bash -c "sleep 7; python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - "db"


  db:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
